-- EcoMart - Database schema for PostgreSQL 15+
-- Based on EcoMart_ERD.md. Run this script on a new/empty database.
--
-- Application-layer invariants enforced OUTSIDE this DDL (see API Specification):
--   * POST /orders/{orderId}/cancel (Customer) must auto-assign
--     cancellation_reason = 'Khách hàng hủy đơn' inside the same transaction,
--     because orders.cancellation_reason is NOT NULL whenever status = 'CANCELLED'
--     regardless of which actor cancelled.
--   * Order creation (POST /orders) must lock the INVENTORY rows for every
--     product in the cart, in ascending product_id order, before re-checking
--     stock and decrementing it: SELECT ... FOR UPDATE. This prevents oversell
--     under concurrent checkouts.
--   * ORDER.total_amount must equal SUM(order_items.line_total) for the order;
--     this is not enforced by a DB constraint and must be covered by tests.

BEGIN;

CREATE TABLE roles (
    role_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(20) NOT NULL UNIQUE,
    description VARCHAR(255),
    CONSTRAINT ck_roles_role_name CHECK (role_name IN ('CUSTOMER', 'MANAGER', 'ADMIN'))
);

CREATE TABLE app_users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id SMALLINT NOT NULL REFERENCES roles(role_id),
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_app_users_full_name CHECK (length(trim(full_name)) > 0),
    CONSTRAINT ck_app_users_email_not_blank CHECK (length(trim(email)) > 0)
);

CREATE UNIQUE INDEX ux_app_users_email_lower ON app_users (lower(email));

CREATE TABLE password_reset_requests (
    reset_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(user_id),
    reset_token VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_password_reset_requests_token CHECK (length(trim(reset_token)) > 0),
    CONSTRAINT ck_password_reset_requests_expiry CHECK (expires_at > created_at)
);
-- used_at stays NULL until the token is consumed; a reset request is valid
-- when used_at IS NULL AND expires_at > now().

CREATE INDEX ix_password_reset_requests_user_id ON password_reset_requests (user_id);

CREATE TABLE addresses (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(user_id),
    recipient_name VARCHAR(150) NOT NULL,
    recipient_phone VARCHAR(20) NOT NULL,
    address_detail VARCHAR(255) NOT NULL,
    ward VARCHAR(150),
    district VARCHAR(150) NOT NULL,
    province VARCHAR(150) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_addresses_recipient_name CHECK (length(trim(recipient_name)) > 0),
    CONSTRAINT ck_addresses_recipient_phone CHECK (length(trim(recipient_phone)) > 0),
    CONSTRAINT ck_addresses_address_detail CHECK (length(trim(address_detail)) > 0)
);

CREATE INDEX ix_addresses_user_id ON addresses (user_id);
CREATE UNIQUE INDEX ux_addresses_one_default_per_user
    ON addresses (user_id) WHERE is_default;

CREATE TABLE categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(150) NOT NULL UNIQUE,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_categories_name CHECK (length(trim(category_name)) > 0)
);

CREATE TABLE brands (
    brand_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name VARCHAR(150) NOT NULL UNIQUE,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_brands_name CHECK (length(trim(brand_name)) > 0)
);

CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES categories(category_id),
    brand_id BIGINT NOT NULL REFERENCES brands(brand_id),
    product_name VARCHAR(255) NOT NULL,
    description TEXT,
    selling_price NUMERIC(14, 2) NOT NULL,
    original_price NUMERIC(14, 2),
    eco_score SMALLINT,
    material_info VARCHAR(500),
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_products_name CHECK (length(trim(product_name)) > 0),
    CONSTRAINT ck_products_selling_price CHECK (selling_price > 0),
    CONSTRAINT ck_products_eco_score CHECK (eco_score IS NULL OR eco_score BETWEEN 1 AND 5),
    CONSTRAINT ck_products_original_price CHECK (original_price IS NULL OR original_price > selling_price)
);

CREATE INDEX ix_products_category_visible ON products (category_id, is_visible);
CREATE INDEX ix_products_brand_visible ON products (brand_id, is_visible);
CREATE INDEX ix_products_visible_price ON products (is_visible, selling_price);
CREATE INDEX ix_products_name_search ON products USING GIN (to_tsvector('simple', product_name));

CREATE TABLE product_images (
    product_image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(product_id),
    image_url VARCHAR(2048) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_product_images_url CHECK (length(trim(image_url)) > 0),
    CONSTRAINT ck_product_images_display_order CHECK (display_order >= 0)
);

CREATE INDEX ix_product_images_product_order ON product_images (product_id, display_order);
CREATE UNIQUE INDEX ux_product_images_one_primary_per_product
    ON product_images (product_id) WHERE is_primary;

CREATE TABLE certifications (
    certification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    certification_name VARCHAR(150) NOT NULL UNIQUE,
    description VARCHAR(500),
    icon_url VARCHAR(2048),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_certifications_name CHECK (length(trim(certification_name)) > 0)
);

CREATE TABLE product_certifications (
    product_id BIGINT NOT NULL REFERENCES products(product_id),
    certification_id BIGINT NOT NULL REFERENCES certifications(certification_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (product_id, certification_id)
);

CREATE INDEX ix_product_certifications_certification_id ON product_certifications (certification_id);

CREATE TABLE inventory (
    product_id BIGINT PRIMARY KEY REFERENCES products(product_id),
    quantity_in_stock INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_inventory_quantity CHECK (quantity_in_stock >= 0)
);
-- Checkout must run:
--   SELECT quantity_in_stock FROM inventory
--   WHERE product_id = ANY(:product_ids) ORDER BY product_id FOR UPDATE;
-- before validating and decrementing stock, to prevent oversell.

CREATE TABLE carts (
    cart_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES app_users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cart_items (
    cart_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL REFERENCES carts(cart_id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(product_id),
    quantity INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_cart_items_cart_product UNIQUE (cart_id, product_id),
    CONSTRAINT ck_cart_items_quantity CHECK (quantity > 0)
);

CREATE INDEX ix_cart_items_product_id ON cart_items (product_id);

CREATE TABLE order_statuses (
    status_code VARCHAR(20) PRIMARY KEY,
    status_name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL
);

CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(user_id),
    status_code VARCHAR(20) NOT NULL REFERENCES order_statuses(status_code),
    order_code VARCHAR(30) NOT NULL UNIQUE,
    payment_method VARCHAR(10) NOT NULL DEFAULT 'COD',
    payment_status VARCHAR(20) NOT NULL DEFAULT 'UNPAID',
    total_amount NUMERIC(14, 2) NOT NULL,
    recipient_name VARCHAR(150) NOT NULL,
    recipient_phone VARCHAR(20) NOT NULL,
    delivery_address VARCHAR(600) NOT NULL,
    cancellation_reason TEXT,
    ordered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    paid_at TIMESTAMPTZ,
    CONSTRAINT ck_orders_code CHECK (length(trim(order_code)) > 0),
    CONSTRAINT ck_orders_total_amount CHECK (total_amount > 0),
    CONSTRAINT ck_orders_payment_method CHECK (payment_method IN ('COD', 'VNPAY', 'SEPAY')),
    CONSTRAINT ck_orders_payment_status CHECK (payment_status IN ('UNPAID', 'PAID', 'FAILED', 'REFUNDED')),
    CONSTRAINT ck_orders_recipient_name CHECK (length(trim(recipient_name)) > 0),
    CONSTRAINT ck_orders_recipient_phone CHECK (length(trim(recipient_phone)) > 0),
    CONSTRAINT ck_orders_delivery_address CHECK (length(trim(delivery_address)) > 0),
    -- cancellation_reason is required for every CANCELLED order, regardless of
    -- actor. When the Customer cancels (no reason collected in the UI), the
    -- API layer must default it to 'Khách hàng hủy đơn' in the same
    -- transaction that flips status_code to CANCELLED.
    CONSTRAINT ck_orders_cancelled_data CHECK (
        (status_code = 'CANCELLED' AND cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL)
        OR (status_code <> 'CANCELLED' AND cancelled_at IS NULL AND cancellation_reason IS NULL)
    ),
    CONSTRAINT ck_orders_confirmed_data CHECK (
        (status_code IN ('CONFIRMED', 'COMPLETED') AND confirmed_at IS NOT NULL)
        OR (status_code NOT IN ('CONFIRMED', 'COMPLETED') AND confirmed_at IS NULL)
    ),
    CONSTRAINT ck_orders_completed_data CHECK (
        (status_code = 'COMPLETED' AND completed_at IS NOT NULL)
        OR (status_code <> 'COMPLETED' AND completed_at IS NULL)
    )
);

CREATE INDEX ix_orders_user_id_ordered_at ON orders (user_id, ordered_at DESC);
CREATE INDEX ix_orders_status_ordered_at ON orders (status_code, ordered_at DESC);

CREATE TABLE order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(order_id),
    product_id BIGINT NOT NULL REFERENCES products(product_id),
    product_name VARCHAR(255) NOT NULL,
    unit_price NUMERIC(14, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    line_total NUMERIC(14, 2) GENERATED ALWAYS AS (unit_price * quantity) STORED,
    CONSTRAINT uq_order_items_order_product UNIQUE (order_id, product_id),
    CONSTRAINT uq_order_items_id_product UNIQUE (order_item_id, product_id),
    CONSTRAINT ck_order_items_product_name CHECK (length(trim(product_name)) > 0),
    CONSTRAINT ck_order_items_unit_price CHECK (unit_price > 0),
    CONSTRAINT ck_order_items_quantity CHECK (quantity > 0)
);
-- orders.total_amount must equal SUM(line_total) for the order. Not enforced
-- here by a constraint/trigger; must be guaranteed by the order-creation
-- transaction and covered by an integration test.

CREATE INDEX ix_order_items_product_id ON order_items (product_id);

CREATE TABLE payment_transactions (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(order_id),
    gateway VARCHAR(20) NOT NULL,
    amount NUMERIC(14, 2) NOT NULL,
    gateway_transaction_no VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    raw_response TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_payment_transactions_gateway CHECK (gateway IN ('VNPAY', 'SEPAY')),
    CONSTRAINT ck_payment_transactions_amount CHECK (amount > 0),
    CONSTRAINT ck_payment_transactions_status CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED'))
);

CREATE INDEX ix_payment_transactions_order_id ON payment_transactions (order_id);
CREATE INDEX ix_payment_transactions_gateway_txno ON payment_transactions (gateway, gateway_transaction_no);

CREATE TABLE reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(user_id),
    product_id BIGINT NOT NULL REFERENCES products(product_id),
    order_item_id BIGINT NOT NULL UNIQUE,
    rating SMALLINT NOT NULL,
    comment TEXT,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reviews_order_item_product
        FOREIGN KEY (order_item_id, product_id)
        REFERENCES order_items(order_item_id, product_id),
    CONSTRAINT ck_reviews_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE INDEX ix_reviews_product_visible_created_at
    ON reviews (product_id, is_visible, created_at DESC);
CREATE INDEX ix_reviews_user_id ON reviews (user_id);

-- A review is allowed only when its order belongs to the reviewer and is
-- completed. Fires only on INSERT or on UPDATE of the eligibility-defining
-- columns, so PATCH /reviews/{id} (rating/comment/is_visible only) does not
-- re-trigger this check — kept equivalent to the SQL Server trigger.
CREATE OR REPLACE FUNCTION validate_review_eligibility()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM order_items oi
        JOIN orders o ON o.order_id = oi.order_id
        WHERE oi.order_item_id = NEW.order_item_id
          AND oi.product_id = NEW.product_id
          AND o.user_id = NEW.user_id
          AND o.status_code = 'COMPLETED'
    ) THEN
        RAISE EXCEPTION 'Review is allowed only for a product in the reviewer''s completed order';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_reviews_validate_eligibility
BEFORE INSERT OR UPDATE OF user_id, product_id, order_item_id ON reviews
FOR EACH ROW
EXECUTE FUNCTION validate_review_eligibility();

CREATE TABLE contact_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL,
    phone VARCHAR(20),
    subject VARCHAR(255),
    content TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ,
    CONSTRAINT ck_contact_messages_full_name CHECK (length(trim(full_name)) > 0),
    CONSTRAINT ck_contact_messages_content CHECK (length(trim(content)) > 0),
    CONSTRAINT ck_contact_messages_status CHECK (status IN ('NEW', 'RESOLVED')),
    CONSTRAINT ck_contact_messages_resolved_data CHECK (
        (status = 'RESOLVED' AND resolved_at IS NOT NULL)
        OR (status = 'NEW' AND resolved_at IS NULL)
    )
);

CREATE INDEX ix_contact_messages_status_created_at ON contact_messages (status, created_at DESC);

CREATE TABLE content_pages (
    page_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(100) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_content_pages_slug CHECK (length(trim(slug)) > 0),
    CONSTRAINT ck_content_pages_title CHECK (length(trim(title)) > 0)
);

CREATE TABLE store_settings (
    setting_key VARCHAR(50) PRIMARY KEY,
    setting_value TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO roles (role_name, description)
VALUES
    ('CUSTOMER', 'Khách hàng mua sản phẩm'),
    ('MANAGER', 'Quản lý vận hành và kinh doanh'),
    ('ADMIN', 'Quản trị viên hệ thống')
ON CONFLICT (role_name) DO NOTHING;

INSERT INTO order_statuses (status_code, status_name, description)
VALUES
    ('PENDING', 'Chờ xác nhận', 'Đơn mới tạo, chờ Admin xử lý'),
    ('CONFIRMED', 'Đã xác nhận', 'Admin đã xác nhận đơn hàng'),
    ('COMPLETED', 'Đã hoàn thành', 'Đơn hàng đã giao thành công'),
    ('CANCELLED', 'Đã hủy', 'Đơn hàng bị Customer hoặc Admin hủy')
ON CONFLICT (status_code) DO NOTHING;

INSERT INTO content_pages (slug, title, content)
VALUES
    ('return-policy', 'Chính sách đổi trả', 'Nội dung chính sách đổi trả — Admin cập nhật.'),
    ('warranty-policy', 'Chính sách bảo hành', 'Nội dung chính sách bảo hành — Admin cập nhật.'),
    ('shipping-policy', 'Chính sách vận chuyển', 'Nội dung chính sách vận chuyển — Admin cập nhật.')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO store_settings (setting_key, setting_value)
VALUES
    ('store_phone', ''),
    ('store_email', ''),
    ('store_address', ''),
    ('map_embed_url', '')
ON CONFLICT (setting_key) DO NOTHING;

COMMIT;
