-- ============================================================
-- V1__baseline.sql
-- Baseline migration: marks the initial database state.
-- Schema is created by Hibernate on first run (ddl-auto=update);
-- Flyway then takes over tracking from this point forward.
-- Subsequent schema changes must be added as V2__..., V3__..., etc.
-- ============================================================

-- Intentionally empty. This file exists to establish a Flyway baseline
-- so that future migrations (V2, V3, ...) can be applied on top of
-- the schema generated by JPA entities.
SELECT 1;
